// ETH32 - an Enemy Territory cheat for windows
// Copyright (c) 2007 eth32 team
// www.cheatersutopia.com & www.nixcoders.org

#pragma once
#define MAX_SETTING_VALUES	31

typedef enum {
	SETTING_INT,
	SETTING_FLOAT,
	SETTING_BOOL,
	SETTING_VEC3,
	SETTING_VEC4,
	SETTING_BYTE3,
	SETTING_STRING,
	MAX_SETTINGS
} settingtype_t;

typedef struct settingvalue_s {
	float value;
	const char *text;
} settingvalue_t;

typedef struct settingdef_s {
	const char *name;
	const char *defaultValue;
	settingtype_t type;
	void *target;
	const char *description;
	float min, max;
	settingvalue_t values[MAX_SETTING_VALUES];
} settingdef_t;

const static settingdef_t settingsDefs[] = 
{
	// Name				Default			Type				Target
	//	Description
	//	Min / Max
	//	  Value				TextValue
	{ "espname",		"true",			SETTING_BOOL,		(void*)&eth32.settings.espName,
		"display player names above their heads",
	},
	{ "esptracker",		"true",			SETTING_BOOL,		(void*)&eth32.settings.espTracker,
		"display ETH32 usernames above their heads",
	},
	{ "icontracker",	"true",			SETTING_BOOL,		(void*)&eth32.settings.iconTracker,
		"display an icon for ETH32 users",
	},
	{ "wallhack",		"true",			SETTING_BOOL,		(void*)&eth32.settings.wallhack,
		"view players and items through walls",
	},
	{ "blackout",		"false",		SETTING_BOOL,		(void*)&eth32.settings.blackout,
		"display the blackout around scoped weapons",
	},
	{ "weapzoom",		"false",		SETTING_BOOL,		(void*)&eth32.settings.weaponZoom,
		"toggle weapon zoom for scoped weapons",
	},
	{ "scopedspeed",	"1.0",			SETTING_FLOAT,		(void*)&eth32.settings.scopedTurnSpeed,
		"determines turning speed while scoped, (normal unscoped speed = 1.0)",
		0.1, 1.0,
	},
	{ "smoketransp",	"18",			SETTING_INT,		(void*)&eth32.settings.smoketrnsp,
		"set the transparency of smoke",
		0,	100,
	},
	{ "respawntimers",	"true",			SETTING_BOOL,		(void*)&eth32.settings.respawnTimers,
		"display friendly and enemy respawn times",
	},
	{ "autotapout",		"false",		SETTING_BOOL,		(void*)&eth32.settings.autoTapout,
		"when killed, auto-tapout and sends you instantly to the reinforcements queue",
	},
	{ "speclist",			"true",			SETTING_BOOL,		(void*)&eth32.settings.getSpeclist,
		 "show who is spectating you",
	},
	{ "nameclick",		"false",		SETTING_BOOL,		(void*)&eth32.settings.nameClick,
		"allows you to click a name in chat window to setup a private message",
	},
		/** *******************************************************************
					AIMBOT
		******************************************************************* **/
	{ "aimmode",			"1",			SETTING_INT,		(void*)&eth32.settings.aimMode,
		"master aimbot mode",
		AIMMODE_OFF, AIMMODE_MAX-1,
		{
			{ (int)AIMMODE_OFF,		"off" },
			{ (int)AIMMODE_NORMAL,		"normal" },
			{ (int)AIMMODE_HUMAN, 		"human" },
		},
	},
	{ "aimtype",			"4",			SETTING_INT,		(void*)&eth32.settings.aimType,
		"determines when the aimbot will activate",
		AIM_OFF, AIM_MAX-1,
		{
			{ (int)AIM_OFF,		"off" },
			{ (int)AIM_ON_FIRE,	"onfire" },
			{ (int)AIM_ON_BUTTON, 	"onbutton" },
			{ (int)AIM_ALWAYS,	"always" },
			{ (int)AIM_TRIGGER,	"trigger" },
		},
	},
	{ "aimsort",		"2",			SETTING_INT,		(void*)&eth32.settings.aimSort,
		"sets type of sort to be used with valid targets",
		SORT_OFF, SORT_MAX-1,
		{
		    
			{ (int)SORT_OFF,	    "off" },
			{ (int)SORT_DISTANCE,	"distance" },
            { (int)SORT_ATTACKER,  		"attacker" },
			{ (int)SORT_CROSSHAIR,	"crosshair" },
			{ (int)SORT_KDRATIO,		"kdratio" },
			{ (int)SORT_ACCURACY,	"accuracy" },
			{ (int)SORT_THREAT,		"threat" },
		},
	},
	{ "autofire",		"false",		SETTING_BOOL,		(void*)&eth32.settings.autofire,
		"aimbot will fire for you when target available\n   (note: autofire must be turned on per weapon as well)",
	},
	{ "locktarget",		"false",		SETTING_BOOL,		(void*)&eth32.settings.lockTarget,
		"once a target is aquired, aimbot will stay on this target while it remains visible",
	},
	{ "headbody",		"4",			SETTING_INT,		(void*)&eth32.settings.headbody,
		"determines if the aimbot uses the head or body and which order",
		0, AP_MAX-1,
		{
			{ (int)BODY_ONLY,		"bodyonly" },
			{ (int)HEAD_ONLY,		"headonly" },
			{ (int)BODY_HEAD,		"bodyfirst" },
			{ (int)HEAD_BODY,		"headfirst" },
			{ (int)HEAD_PRIORITY,	"headpriority" },
		},
	},
	{ "atkvalid",		"false",		SETTING_BOOL,		(void*)&eth32.settings.atkValidate,
		"inhibits firing, even manually, until a valid target is visible",
	},
	{ "antitk",			"false",		SETTING_BOOL,		(void*)&eth32.settings.antiTk,
		"returns fire to teamkillers",
	},
	{ "nudgehack",			"false",		SETTING_BOOL,		(void*)&eth32.settings.nudgeHack,
		"unprotects cl_timenudge cvar so it can be used in any server",
	},
	{ "autodelay",			"true",		SETTING_BOOL,		(void*)&eth32.settings.autoDelay,
		"auto weapon delay",
	},
	{ "hitboxtype",			"1",			SETTING_INT,		(void*)&eth32.settings.hitboxType,
		"set the hitbox style to use for aimbot",
		HITBOX_OFF, HITBOX_MAX-1,
		{
			{ (int)HITBOX_OFF,		"off" },
			{ (int)HITBOX_CUSTOM,		"custom" },
		},
	},
	{ "headtracetype",			"2",			SETTING_INT,		(void*)&eth32.settings.headTraceType,
		"set the style of trace used to determine if a target is visible",
		0, HEAD_MAX-1,
		{
			{ (int)HEAD_CENTER,		"center" },
			{ (int)HEAD_STATIC,		"static" },
			{ (int)HEAD_XTRACE,		"xtrace" },
		},
	},
	{ "bodytracetype",			"2",			SETTING_INT,		(void*)&eth32.settings.bodyTraceType,
		"set the style of trace used to determine if a target is visible",
		0, BODY_MAX-1,
		{
			{ (int)BODY_CENTER,		"center" },
			{ (int)BODY_CONTOUR,		"contour" },
			{ (int)BODY_STATIC,		"static" },
			{ (int)BODY_XTRACE,		"xtrace" },
			{ (int)BODY_RANDOM_VOLUME,	"randvolume" },
			{ (int)BODY_RANDOM_SURFACE,	"randsurface" },
            		{ (int)BODY_CAPSULE_VOLUME,	"capvolume" },
            		{ (int)BODY_CAPSULE_SURFACE,	"capsurface" },
		},
	},
	{ "trans_console",	"true",	SETTING_BOOL, (void*)&eth32.settings.transparantConsole,
		"make the console transparant so you can see whats going on :)"
	}, 
	{ "valgrentraj", "false",		SETTING_BOOL, (void*)&eth32.settings.valGrenTrajectory,
		"make additional calculations to make sure the grenade doesn't hit anything",
	},
	{ "valrifletraj", "true",		SETTING_BOOL, (void*)&eth32.settings.valRifleTrajectory,
		"make additional calculations to make sure the riflegrenade doesn't hit anything",
	},
	{ "grenadeZ",	"0.0",				SETTING_FLOAT,	(void*)&eth32.settings.grenadeZ,
		"z correction for grenade aimpoint",
	},
	{ "riflenadeZ",	"-10.0",			SETTING_FLOAT,	(void*)&eth32.settings.riflenadeZ,
		"z correction for rifle grenade aimpoint",
	},
	{ "grenadeautofire", "true",	SETTING_BOOL,	(void*)&eth32.settings.grenadeAutoFire,
		"auto-fire grenade so it will explode right on contact",
	},
	{ "rifleautofire", "true",		SETTING_BOOL,	(void*)&eth32.settings.rifleAutoFire,
		"auto-fire riflegrenade as soon as we have a firing solution",
	},
	{ "grenadetracer", "true",	    SETTING_BOOL,				(void*)&eth32.settings.grenadeTracer,
		"shows trajectory of the grenade",
	},
	{ "rifletracer", "true",	     SETTING_BOOL,				(void*)&eth32.settings.rifleTracer,
		"shows trajectory of the rifle grenade",
	},
	{ "grensenslock", "false",	    SETTING_BOOL,				(void*)&eth32.settings.grenadeSenslock,
		"locks view if there is a valid firing solution",
	},
	{ "grenadebot", "true",	        SETTING_BOOL,				(void*)&eth32.settings.grenadeBot,
		"toggles the grenade aimbot",
	},
	{ "riflebot", "true",	        SETTING_BOOL,				(void*)&eth32.settings.rifleBot,
		"toggles the riflegrenade aimbot",
	},
	{ "grenblockfire", "true",	     SETTING_BOOL,				(void*)&eth32.settings.grenadeBlockFire,
		"blocks firing grenades by accident if there isn't a firing solution",
	},
	{ "grenfiredelay",	"300",			SETTING_INT,		(void*)&eth32.settings.grenadeFireDelay,
		"the time it takes when releasing fire button and the grenade is launched (leave if you dont know what you're doing)",
		0, 1000,
	},
	{ "radiusdamage_enable", "false",	SETTING_BOOL,				(void*)&eth32.settings.ballisticRadiusDamage,
		"if target is not visible, try a point within the grenade's blast radius",
	},
	{ "radiusdamage",	"200.0",			SETTING_FLOAT,		(void*)&eth32.settings.radiusDamage,
		"the grenade blast radius to use",
		30, 1000,
	},
	{ "grenpredict",		"1",			SETTING_INT,		(void*)&eth32.settings.ballisticPredict,
		"predict targets for grenade aimbot",
		0, RF_PREDICT_MAX-1,
		{
				{ (int)RF_PREDICT_OFF, 		"off" },
				{ (int)RF_PREDICT_LINEAR, 	"linear" },
				{ (int)RF_PREDICT_LINEAR2, 	"linear/2" },
				{ (int)RF_PREDICT_AVG, 		"average pos" },
				{ (int)RF_PREDICT_SMART, 	"smart" },
		}
	},
	{ "grenautotarg",	"true",			SETTING_BOOL,		(void*)&eth32.settings.autoGrenTargets,
		"automatically selects grenade targets based on crosshair distance",
	},
	{ "grenblockfire", "true",	SETTING_BOOL,				(void*)&eth32.settings.grenadeBlockFire,
		"blocks firing grenades by accident if there isn't a firing solution",
	},
	{ "fov",			"360.0",		SETTING_FLOAT,		(void*)&eth32.settings.fov,
		"set the field of vision that the aimbot can select targets from",
		0, 360,
	},
	{ "multibounce",		"true",			SETTING_BOOL,		(void*)&eth32.settings.allowMultiBounce,
		"use extra CPU to calculate secondary trajectories with multiple bounces off walls",
	},

	{ "humanMode",			"1",			SETTING_INT,		(void*)&eth32.settings.humanMode,
		"which human method should be used",
		HUMAN_AIM_HALF_LOGINS, HUMAN_AIM_MAX-1,
		{
			{ (int)HUMAN_AIM_HALF_LOGINS,	"simple" },
			{ (int)HUMAN_AIM_FULL_LOGINS,	"full" },
		},
	},
	{ "human1_speed",		"0.05",			SETTING_FLOAT,		(void*)&eth32.settings.human1_speed,
		 "Simple Logins - Speed",
 		0, 0.2,
 	},
	{ "human2_humanValue",		"0.065",		SETTING_FLOAT,		(void*)&eth32.settings.human2_humanValue,
		 "FULL Logins - divMax",
 		0, 0.2,
 	},
	{ "human2_aimX",		"5.9",			SETTING_FLOAT,		(void*)&eth32.settings.human2_aimX,
		 "FULL Logins - SpeedX",
 		0, 10,
 	},
	{ "human2_aimY",		"10",			SETTING_FLOAT,		(void*)&eth32.settings.human2_aimY,
		 "FULL Logins - SpeedY",
 		0, 10,
 	},
	{ "human2_divMin",		"3.75",			SETTING_FLOAT,		(void*)&eth32.settings.human2_divMin,
		 "FULL Logins - divMin",
 		0, 10,
 	},
	{ "human2_divMax",		"5",			SETTING_FLOAT,		(void*)&eth32.settings.human2_divMax,
		 "FULL Logins - divMax",
 		0, 10,
 	},
 	{ "aimprotect",			"0",			SETTING_INT,		(void*)&eth32.settings.aimprotect,
		"turn off aimbot when people are watching",
		0, PROTECT_MAX-1,
		{
			{ (int)PROTECT_OFF,		"off" },
			{ (int)PROTECT_SPECS,		"specs" },
			{ (int)PROTECT_ALL,		"all" },
		},
	},
	{ "lockMouse",			"false",		SETTING_BOOL,		(void*)&eth32.settings.lockMouse,
		 "Lock mouse while aiming",
	},
	{ "randomaim",			"true",			SETTING_BOOL,		(void*)&eth32.settings.randomAim,
		 "enables randomized aiming for human mode",
	},
	{ "shakefreq",			"7000",			SETTING_INT,		(void*)&eth32.settings.shakeFreq,
		 "set how often the aim will bounce randomly (in ms)",
		1, 20000,
	},
	{ "randfactx",	   		"470",	    		SETTING_INT,		(void*)&eth32.settings.randFactX,
		"amount of randomness for random aim in the X axis",
		0, 1000,
	},
	{ "randfacty",	   		"470",	    		SETTING_INT,		(void*)&eth32.settings.randFactY,
		"amount of randomness for random aim in the Y axis",
		0, 1000,
	},
	{ "randfactz",	   		"700",	    		SETTING_INT,		(void*)&eth32.settings.randFactZ,
		"amount of randomness for random aim in the Z axis",
		0, 1000,
	},
	
	/** *******************************************************************
					AIMBOT EXTRA
	******************************************************************* **/
	{ "headsize",	   		"10",	    		SETTING_FLOAT,		(void*)&eth32.settings.headBoxSize,
		"head hitbox size",
		1, 15,
	},
	{ "bodysize",			"38",			SETTING_FLOAT,		(void*)&eth32.settings.bodybox,
		"body hitbox size",
		0, 40,
	},
	{ "predbot",			"-0.050",		SETTING_FLOAT,		(void*)&eth32.settings.predbot,
		"set amount of prediction to be applied to (bot) targets",
		-1.0, 1.0,
	},
    { "pred",			"-0.005",		SETTING_FLOAT,		(void*)&eth32.settings.pred,
		"set amount of prediction to be applied to (human) targets",
		-1.0, 1.0,
	},
	{ "delayclose",	   	"0",	   		SETTING_INT,		(void*)&eth32.settings.delayClose,
		"weapon delay for close distance",
		0, 50,
	},
	{ "delaymed",	   	"11",	   		SETTING_INT,		(void*)&eth32.settings.delayMed,
		"weapon delay for close distance",
		0, 50,
	},
	{ "delayfar",	   		"16",	    		SETTING_INT,		(void*)&eth32.settings.delayFar,
		"weapon delay for far distance",
		0, 50,
	},
	{ "bulletsize",			"1",			SETTING_INT,		(void*)&eth32.settings.bulletSize,
		"adjust bullet size to prevent shooting at wall instead of players when they're not visible",
		0, 5,
	},
	{ "predself",		"-0.020",			SETTING_FLOAT,		(void*)&eth32.settings.predSelf,
		"set amount to prediction to applied to our own movement (only for manual)",
		-1, 1,
	},
	{ "predself_type",		"3",			SETTING_INT,		(void*)&eth32.settings.predSelfType,
		"set the type of self prediction to apply",
		0, SPR_MAX-1,
		{
			{ (int)SPR_OFF,		"off" },
			{ (int)SPR_MANUAL,	"manual" },
			{ (int)SPR_PING,	"ping" },
			{ (int)SPR_LEET,	"leet" },
		},
	},
	{ "vecstand",			"0.380 -0.300 6.000",		SETTING_VEC3,		(void*)eth32.settings.vecStand,
		"set the hitbox center point for a standing player",
	},
	{ "vecrun",			"0.000 0.000 6.000",		SETTING_VEC3,		(void*)eth32.settings.vecRun,
		"set the hitbox center point for a running player",
	},
	{ "veccrouch",			"-0.500 -0.240 5.500",		SETTING_VEC3,		(void*)eth32.settings.vecCrouch,
		"set the hitbox center point for a crouching player",
	},
	{ "veccrawl",			"0.000 0.000 5.500",		SETTING_VEC3,		(void*)eth32.settings.vecCrawl,
		"set the hitbox center point for a crawling player",
	},
	{ "vecprone",			"0.450 0.240 6.450",		SETTING_VEC3,		(void*)eth32.settings.vecProne,
		"set the hitbox center point for a prone player",
	},	
	{ "dynamicHitbox",	"0.0",			SETTING_FLOAT,		(void*)&eth32.settings.dynamicHitboxScale,
		"set how much a hitbox will scale based on player movement",
		0, 3,
	},
	{ "killspam",		"false",		SETTING_BOOL,		(void*)&eth32.settings.killSpam,
		"enable automated message when a target is killed",
	},
	{ "killsounds",			"true",			SETTING_BOOL,		(void*)&eth32.settings.killSounds,
		"enables sounds to be played when a player is killed",
	},
	{ "randomsounds",		"true",			SETTING_BOOL,		(void*)&eth32.settings.randomSpreeSounds,
		"pick up random spree sounds instead of the classic sequential style",
	},
	{ "hitsounds",			"0",			SETTING_INT,		(void*)&eth32.settings.hitsounds,
		"set the hitsound effect to be used",
		0, HIT_MAX-2,
		{
			{ (int)HIT_OFF,			"off" },
			{ (int)HIT_HEAD,		"head" },
			{ (int)HIT_HEADSHOT,		"headshot" },
			{ (int)HIT_BODY,		"body" },
		},
	},
	{ "puresounds",			"false",		SETTING_BOOL,		(void*)&eth32.settings.pureSounds,
		"only play pure sounds, this will disable anoying custom voicechats",
	},
	{ "hqsounds", 			"false",		SETTING_BOOL,		(void*)&eth32.settings.hqSounds,
		"play HQ sounds (like 'Dynamite Planted')",
	},
	{ "mkillresettime",		"3000",			SETTING_FLOAT,		(void*)&eth32.settings.mkResetTime,
		"period in milliseconds after which multikill sound gets reset",
		0, 10000,
	},
	{ "radarrange",		"3000.0",		SETTING_FLOAT,		(void*)&eth32.settings.radarRange,
		"set the range of the radar window",
		100, 10000,
	},
    { "xhairsize",			"60",			SETTING_FLOAT,		(void*)&eth32.settings.crossSize,
		"sets custom crosshair size",
		0, 500,
	},
	{ "xhairtype",			"3",			SETTING_INT,		(void*)&eth32.settings.customXhair,
		"set the custom crosshair type",
		XHAIR_OFF, XHAIR_MAX-1,
		{
			{ (int)XHAIR_OFF,		"off" },
			{ (int)XHAIR_SNIPER,		"sniper" },
			{ (int)XHAIR_CROSS, 		"opencross" },
			{ (int)XHAIR_CROSS2, 		"opencross2" },
			{ (int)XHAIR_CROSS3,		"closedcross" },
			{ (int)XHAIR_DOT,		"dot" },
		},
	},	
	{ "removefoliage",		"true",			SETTING_BOOL,		(void*)&eth32.settings.removeFoliage,
		"completely removes the foliage (trees, bushes, etc)",
	},
	{ "warningmsgs",		"true",			SETTING_BOOL,		(void*)&eth32.settings.showReload,
		"draw warning messages ('RELOADING', 'LOW AMMO', etc)",
	},
	{ "dmgindicator",		"3",			SETTING_INT,		(void*)&eth32.settings.dmgIndicator,
		"draw damage indicator",
		0, DMG_MAX-1,
		{
			{ (int)DMG_OFF,		"off" },
			{ (int)DMG_HEALTH,	"health" },
			{ (int)DMG_ARROW,	"arrow" },
			{ (int)DMG_HP_ARR,	"health_arrow" },
		},
	},
	{ "dmgarrowsize", 		"96",			SETTING_FLOAT, 		(void*)&eth32.settings.dmgArrSize,
		"sets size of the damage indicator arrow",
		24, 128,
	},
	{ "removeparticles",		"true",			SETTING_BOOL,		(void*)&eth32.settings.removeParticles,
		"remove smoke particles when hitting other players",
	},
    { "autovote",			"false",		SETTING_BOOL,		(void*)&eth32.settings.autoVote,
		"enables autovoting (vote no) against vote kicks",
	},
	{ "autocomplaint",		"false",		SETTING_BOOL,		(void*)&eth32.settings.autoComplaint,
		"enable auto filing complaint when someone teamkills you",
	},	
	/** *******************************************************************
					VISUAL EXTRA
	******************************************************************* **/
	{ "teamshader1",		"11",			SETTING_INT,		(void*)&eth32.settings.teamShader1,
		"set the style of chams to be applied to players",
		SHADER1_OFF, SHADER1_MAX-1,
		{
			{ (int)SHADER1_OFF,		"off" },
			{ (int)SHADER1_KERAMIC,		"keramic" },
			{ (int)SHADER1_CRISPWAVE,	"crispwave" },
			{ (int)SHADER1_CRYSTAL,		"crystal_a" },
			{ (int)SHADER1_CRYSTALB,	"crystal_b" },
			{ (int)SHADER1_GLOW,		"glow" },
			{ (int)SHADER1_FLAME,		"flame" },
			{ (int)SHADER1_SOLIDA,		"solid_a" },
			{ (int)SHADER1_SOLIDB,		"solid_b" },
			{ (int)SHADER1_QUADRED,		"quadred" },
			{ (int)SHADER1_QUADBLUE,	"quadblue" },
			{ (int)SHADER1_QUADMATRIXBLUE,	"quadmblue" },
			{ (int)SHADER1_QUADPURPLE,	"quadpurple" },
			{ (int)SHADER1_QUADGREEN,	"quadgreen" },
			{ (int)SHADER1_QUADYELLOW,	"quadyellow" },
 			{ (int)SHADER1_QUADBROWN,	"quadbrown" },
 			{ (int)SHADER1_QUADCYAN,	"quadcyan" },		
			{ (int)SHADER1_QUADA,		"quad_a" },			
			{ (int)SHADER1_QUADB,		"quad_b" },
			{ (int)SHADER1_QUADC,		"quad_c" },
			{ (int)SHADER1_QUADD,		"quad_d" },
			{ (int)SHADER1_MATRIX,		"matrix" },
			{ (int)SHADER1_THERMAL,		"thermal" },
      			{ (int)SHADER1_XRAY,		"xray" },
      			{ (int)SHADER1_GRID,		"grid" },
     			{ (int)SHADER1_WAVE,		"wave" },
      			{ (int)SHADER1_CRISPY,		"crispy" },
      			{ (int)SHADER1_MARBLE,		"marble" },
      			{ (int)SHADER1_PLASMA,		"plasma" },
      			{ (int)SHADER1_PLASTIC,		"plastic" },
      			{ (int)SHADER1_TEST,		"test" },
		},
	},
	{ "teamshader1wallhack",	"true",			SETTING_BOOL,		(void*)&eth32.settings.teamShader1Wallhack,
		"enable wallhack for players 1st shader",
	},
	{ "teamshader2",		"6",			SETTING_INT,		(void*)&eth32.settings.teamShader2,
		"set the style of chams to be applied to players outline",
		SHADER2_OFF, SHADER2_MAX-1,
		{
			{ (int)SHADER2_OFF,		"off" },
			{ (int)SHADER2_ORIG,		"original" },
			{ (int)SHADER2_MARBLE,		"marble" },
			{ (int)SHADER2_CRYSTAL,		"crystal" },
			{ (int)SHADER2_THERMAL,		"thermal" },
			{ (int)SHADER2_QUAD,		"quad" },
			{ (int)SHADER2_PLASMA,		"plasma" },
			{ (int)SHADER2_PLASTIC,		"plastic" },
		},
	},
	{ "teamshader2wallhack",	"true",			SETTING_BOOL,		(void*)&eth32.settings.teamShader2Wallhack,
		"enable wallhack for players 2nd shader",
	},
	
	{ "enemyshader1",		"11",			SETTING_INT,		(void*)&eth32.settings.enemyShader1,
		"set the style of chams to be applied to players",
		SHADER1_OFF, SHADER1_MAX-1,
		{
			{ (int)SHADER1_OFF,		"off" },
			{ (int)SHADER1_KERAMIC,		"keramic" },
			{ (int)SHADER1_CRISPWAVE,	"crispwave" },
			{ (int)SHADER1_CRYSTAL,		"crystal_a" },
			{ (int)SHADER1_CRYSTALB,	"crystal_b" },
			{ (int)SHADER1_GLOW,		"glow" },
			{ (int)SHADER1_FLAME,		"flame" },
			{ (int)SHADER1_SOLIDA,		"solid_a" },
			{ (int)SHADER1_SOLIDB,		"solid_b" },
			{ (int)SHADER1_QUADRED,		"quadred" },
			{ (int)SHADER1_QUADBLUE,	"quadblue" },
			{ (int)SHADER1_QUADMATRIXBLUE,	"quadmblue" },
			{ (int)SHADER1_QUADPURPLE,	"quadpurple" },
			{ (int)SHADER1_QUADGREEN,	"quadgreen" },
			{ (int)SHADER1_QUADYELLOW,	"quadyellow" },
 			{ (int)SHADER1_QUADBROWN,	"quadbrown" },
 			{ (int)SHADER1_QUADCYAN,	"quadcyan" },		
			{ (int)SHADER1_QUADA,		"quad_a" },			
			{ (int)SHADER1_QUADB,		"quad_b" },
			{ (int)SHADER1_QUADC,		"quad_c" },
			{ (int)SHADER1_QUADD,		"quad_d" },
			{ (int)SHADER1_MATRIX,		"matrix" },
			{ (int)SHADER1_THERMAL,		"thermal" },
      			{ (int)SHADER1_XRAY,		"xray" },
      			{ (int)SHADER1_GRID,		"grid" },
     			{ (int)SHADER1_WAVE,		"wave" },
      			{ (int)SHADER1_CRISPY,		"crispy" },
      			{ (int)SHADER1_MARBLE,		"marble" },
      			{ (int)SHADER1_PLASMA,		"plasma" },
      			{ (int)SHADER1_PLASTIC,		"plastic" },
      			{ (int)SHADER1_TEST,		"test" },
		},
	},
	{ "enemyshader1wallhack",	"true",			SETTING_BOOL,		(void*)&eth32.settings.enemyShader1Wallhack,
		"enable wallhack for players 1st shader",
	},
	{ "enemyshader2",		"6",			SETTING_INT,		(void*)&eth32.settings.enemyShader2,
		"set the style of chams to be applied to players outline",
		SHADER2_OFF, SHADER2_MAX-1,
		{
			{ (int)SHADER2_OFF,		"off" },
			{ (int)SHADER2_ORIG,		"original" },
			{ (int)SHADER2_MARBLE,		"marble" },
			{ (int)SHADER2_CRYSTAL,		"crystal" },
			{ (int)SHADER2_THERMAL,		"thermal" },
			{ (int)SHADER2_QUAD,		"quad" },
			{ (int)SHADER2_PLASMA,		"plasma" },
			{ (int)SHADER2_PLASTIC,		"plastic" },
		},
	},
	{ "enemyshader2wallhack",	"true",			SETTING_BOOL,		(void*)&eth32.settings.enemyShader2Wallhack,
		"enable wallhack for players 2nd shader",
	},
	
	{ "weaponshader1",		"0",			SETTING_INT,		(void*)&eth32.settings.weaponShader1,
		"set the style of chams to be applied to weapons",
		SHADER3_OFF, SHADER3_MAX-1,
		{
			{ (int)SHADER3_OFF,		"off" },
			{ (int)SHADER3_KERAMIC,		"keramic" },
			{ (int)SHADER3_CRISPWAVE,	"crispwave" },
			{ (int)SHADER3_CRYSTAL,		"crystal_a" },
			{ (int)SHADER3_CRYSTALB,	"crystal_b" },
			{ (int)SHADER3_GLOW,		"glow" },
			{ (int)SHADER3_FLAME,		"flame" },
			{ (int)SHADER3_SOLIDA,		"solid_a" },
			{ (int)SHADER3_SOLIDB,		"solid_b" },
			{ (int)SHADER3_WQUADRED,	"wquadred" },
			{ (int)SHADER3_WQUADBLUE,	"wquadblue" },
			{ (int)SHADER3_WQUADMATRIXBLUE,	"wquadmblue" },
			{ (int)SHADER3_WQUADPURPLE,	"wquadpurple" },
			{ (int)SHADER3_WQUADGREEN,	"wquadgreen" },
			{ (int)SHADER3_WQUADYELLOW,	"wquadyellow" },
 			{ (int)SHADER3_WQUADBROWN,	"wquadbrown" },
 			{ (int)SHADER3_WQUADCYAN,	"wquadcyan" },	
			{ (int)SHADER3_QUADA,		"quad_a" },			
			{ (int)SHADER3_QUADB,		"quad_b" },
			{ (int)SHADER3_QUADC,		"quad_c" },
			{ (int)SHADER3_QUADD,		"quad_d" },
			{ (int)SHADER3_MATRIX,		"matrix" },
			{ (int)SHADER3_THERMAL,		"thermal" },
      			{ (int)SHADER3_XRAY,		"xray" },
      			{ (int)SHADER3_GRID,		"grid" },
     			{ (int)SHADER3_WAVE,		"wave" },
      			{ (int)SHADER3_CRISPY,		"crispy" },
      			{ (int)SHADER3_MARBLE,		"marble" },
      			{ (int)SHADER3_PLASMA,		"plasma" },
      			{ (int)SHADER3_PLASTIC,		"plastic" },
      			{ (int)SHADER3_TEST,		"test" },
		},
	},
	{ "weaponshader1wallhack",	"true",			SETTING_BOOL,		(void*)&eth32.settings.weaponShader1Wallhack,
		"enable wallhack for weapons 1st shader",
	},
	{ "weaponshader2",		"0",			SETTING_INT,		(void*)&eth32.settings.weaponShader2,
		"set the style of chams to be applied to weapons outline",
		SHADER4_OFF, SHADER4_MAX-1,
		{
			{ (int)SHADER4_OQUADRED,	"oquadred" },
			{ (int)SHADER4_OQUADBLUE,	"oquadblue" },
			{ (int)SHADER4_OQUAD,		"oquad" },
			{ (int)SHADER4_OMARBLE,		"omarble" },
			{ (int)SHADER4_OCRYSTAL,	"ocrystal" },
			{ (int)SHADER4_OTHERMAL,	"othermal" },
		},
	},
	{ "weaponshader2wallhack",	"true",			SETTING_BOOL,		(void*)&eth32.settings.weaponShader2Wallhack,
		"enable wallhack for weapons 2nd shader",
	},
	
	{ "itemshader1",		"11",			SETTING_INT,		(void*)&eth32.settings.itemShader1,
		"set the style of chams to be applied to items",
		SHADER3_OFF, SHADER3_MAX-1,
		{
			{ (int)SHADER3_OFF,		"off" },
			{ (int)SHADER3_KERAMIC,		"keramic" },
			{ (int)SHADER3_CRISPWAVE,	"crispwave" },
			{ (int)SHADER3_CRYSTAL,		"crystal_a" },
			{ (int)SHADER3_CRYSTALB,	"crystal_b" },
			{ (int)SHADER3_GLOW,		"glow" },
			{ (int)SHADER3_FLAME,		"flame" },
			{ (int)SHADER3_SOLIDA,		"solid_a" },
			{ (int)SHADER3_SOLIDB,		"solid_b" },
			{ (int)SHADER3_WQUADRED,	"wquadred" },
			{ (int)SHADER3_WQUADBLUE,	"wquadblue" },
			{ (int)SHADER3_WQUADMATRIXBLUE,	"wquadmblue" },
			{ (int)SHADER3_WQUADPURPLE,	"wquadpurple" },
			{ (int)SHADER3_WQUADGREEN,	"wquadgreen" },
			{ (int)SHADER3_WQUADYELLOW,	"wquadyellow" },
 			{ (int)SHADER3_WQUADBROWN,	"wquadbrown" },
 			{ (int)SHADER3_WQUADCYAN,	"wquadcyan" },	
			{ (int)SHADER3_QUADA,		"quad_a" },			
			{ (int)SHADER3_QUADB,		"quad_b" },
			{ (int)SHADER3_QUADC,		"quad_c" },
			{ (int)SHADER3_QUADD,		"quad_d" },
			{ (int)SHADER3_MATRIX,		"matrix" },
			{ (int)SHADER3_THERMAL,		"thermal" },
      			{ (int)SHADER3_XRAY,		"xray" },
      			{ (int)SHADER3_GRID,		"grid" },
     			{ (int)SHADER3_WAVE,		"wave" },
      			{ (int)SHADER3_CRISPY,		"crispy" },
      			{ (int)SHADER3_MARBLE,		"marble" },
      			{ (int)SHADER3_PLASMA,		"plasma" },
      			{ (int)SHADER3_PLASTIC,		"plastic" },
      			{ (int)SHADER3_TEST,		"test" },	
		},
	},
	{ "itemshader1wallhack",	"true",			SETTING_BOOL,		(void*)&eth32.settings.itemShader1Wallhack,
		"enable wallhack for items 1st shader",
	},
	{ "itemshader2",		"6",			SETTING_INT,		(void*)&eth32.settings.itemShader2,
		"set the style of chams to be applied to items outline",
		SHADER4_OFF, SHADER4_MAX-1,
		{
			{ (int)SHADER4_OQUADRED,	"oquadred" },
			{ (int)SHADER4_OQUADBLUE,	"oquadblue" },
			{ (int)SHADER4_OQUAD,		"oquad" },
			{ (int)SHADER4_OMARBLE,		"omarble" },
			{ (int)SHADER4_OCRYSTAL,	"ocrystal" },
			{ (int)SHADER4_OTHERMAL,	"othermal" },
		},
	},
	{ "itemshader2wallhack",	"true",			SETTING_BOOL,		(void*)&eth32.settings.itemShader2Wallhack,
		"enable wallhack for items 2nd shader",
	},

	{ "colorteam",		"0 255 0",		SETTING_BYTE3,		(void*)eth32.settings.colorTeam,
		"set the color of team chams",
	},
	{ "colorteamout",		"0 0 255",	SETTING_BYTE3,		(void*)eth32.settings.colorTeamOut,
		"set the color of team outline",
	},
	{ "colorteamhid",	"0 100 0",	SETTING_BYTE3,		(void*)eth32.settings.colorTeamHidden,
		"set the color of team chams when hidden",
	},
	{ "colorenemy",		"255 0 0",	SETTING_BYTE3,		(void*)eth32.settings.colorEnemy,
		"set the color of enemy chams",
	},
	{ "colorenemyout",		"255 0 255",	SETTING_BYTE3,		(void*)eth32.settings.colorEnemyOut,
		"set the color of enemy outline",
	},
	{ "colorenemyhid",	"100 0 0",		SETTING_BYTE3,		(void*)eth32.settings.colorEnemyHidden,
		"set the color of enemy chams when hidden",
	},
	{ "colorinvuln",	"255 255 0",	SETTING_BYTE3,		(void*)eth32.settings.colorInvulnerable,
		"set the color of player chams when they are invulnerable",
	},
    { "enemyweapoutline",		"0 0 255",	SETTING_BYTE3,		(void*)eth32.settings.EnemyWeaponOutline,
		"set the color of Team weapon outchams",
	},
	{ "weaponoutline",		"0 0 255",	SETTING_BYTE3,		(void*)eth32.settings.TeamWeaponOutline,
		"set the color of Team weapon outchams",
	},
	{ "colorteamweap",	"0 255 255",	SETTING_BYTE3,		(void*)eth32.settings.colorTeamWeapon,
		"set the color of team weapons",
	},
	{ "colorenemyweap", "255 75 0",	SETTING_BYTE3,		(void*)eth32.settings.colorEnemyWeapon,
		"set the color of enemy weapons",
	},
	{ "colorhealth",	"255 0 0",		SETTING_BYTE3,		(void*)eth32.settings.colorHealth,
		"set the color of health kits",
	},
	{ "colorhealthoutline",		"230 0 255",		SETTING_BYTE3,		(void*)eth32.settings.colorHealthOutline,
		"set the color of health kits outline",
	},
	{ "colorammo",		"0 255 0",		SETTING_BYTE3,		(void*)eth32.settings.colorAmmo,
		"set the color of ammo boxes",
	},
	{ "colorammooutline",		"0 0 255",		SETTING_BYTE3,		(void*)eth32.settings.colorAmmoOutline,
		"set the color of ammo boxes outline",
	},
	{ "colorworldweapons",		"0 0 255",		SETTING_BYTE3,		(void*)eth32.settings.colorWorldWeapons,
		"set the color of ammo boxes",
	},
	{ "colorworldweaponsoutline",	"0 0 255",		SETTING_BYTE3,		(void*)eth32.settings.colorWorldWeaponsOutline,
		"set the color of ammo boxes",
	},
	//Class ESP Color
	{ "classteam",			"0 1 0",		SETTING_VEC3,		(void*)eth32.settings.clsTeam,
		"set the color of team class esp",
	},
	{ "classenemy",			"1 0 0",		SETTING_VEC3,		(void*)eth32.settings.clsEnemy,
		"set the color of team class esp",
	},
	{ "classopacity",		"0.8",			SETTING_FLOAT,		(void*)&eth32.settings.clsOpacity,
		"sets the class icon esp opacity",
		0, 1,
	},
	{ "itemesp",			"true",			SETTING_BOOL,		(void*)&eth32.settings.itemEsp,
		"display health and ammo esp icons",
	},
	{ "itemespsize",		"14",			SETTING_FLOAT,		(void*)&eth32.settings.itemEspSize,
		"set the health and ammo icon esp size",
		0, 30,
	},
	{ "itemespopacity",		"0.8",			SETTING_FLOAT,		(void*)&eth32.settings.itemEspOpacity,
		"set the health and ammo icon esp opacity",
		0, 1,
	},
	{ "boxesp",			"true",			SETTING_BOOL,		(void*)&eth32.settings.boxEsp,
		"display a box around players",
	},
	{ "boxespborder",		"1",			SETTING_INT,		(void*)&eth32.settings.boxEspBorder,
		"set the box esp border size",
		0, 5,
	},
	{ "boxespopacity",		"0.8",			SETTING_FLOAT,		(void*)&eth32.settings.boxEspOpacity,
		"set the box esp opacity",
		0, 1,
	},
	{ "ircchatmsgs",	"0",			SETTING_INT,		(void*)&eth32.settings.ircChatMsgs,
		"set which IRC channels are routed to main chat window",
		0, IRC_ROUTING_MAX-1,
		{
			{ (int)IRC_ROUTING_OFF,		"off" },
			{ (int)IRC_ROUTING_CURRENT,	"current" },
			{ (int)IRC_ROUTING_ALL,		"all" },
		},
	},
	{ "ircconsolemsgs",	"0",			SETTING_INT,		(void*)&eth32.settings.ircConsoleMsgs,
		"set which IRC channels are routed to console",
		0, IRC_ROUTING_MAX-1,
		{
			{ (int)IRC_ROUTING_OFF,		"off" },
			{ (int)IRC_ROUTING_CURRENT,	"current" },
			{ (int)IRC_ROUTING_ALL,		"all" },
		}
	},
	{ "ircmention",		"false",		SETTING_BOOL,		(void*)&eth32.settings.ircMention,
		"enable notification if someone mentions your player name or ETH32 username in IRC",
	},
	{ "coop",		"1",			SETTING_INT,		(void*)&eth32.settings.portalCoopMode,
		"set who you want to play cooperatively with",
		0, COOP_MAX-1,
		{
			{ (int)COOP_OFF,		"off" },
			{ (int)COOP_FRIENDS, "friends" },
			{ (int)COOP_ALL,		"all" },	
		},
	},
	{ "portalanon",		"false",		SETTING_BOOL,		(void*)&eth32.settings.portalAnon,
		"enable anonymity on portal, others will not be able to tell which server you are on",
	},
	{ "rampagenum",		"5",			SETTING_INT,		(void*)&eth32.settings.portalRampageNum,
		"set the minimum number of players to qualify as a rampage",
		4, 32,
	},
	{ "rampagenotify",	"true",			SETTING_BOOL,		(void*)&eth32.settings.portalRampageNotify,
		"enable notification of rampages in progress",
	},
	
	// hitbox drawing, custom tracers
	{ "headhitbox",		"true",			SETTING_BOOL,		(void*)&eth32.settings.drawHeadHitbox,
		"enable head hitbox drawing",
	},
	{ "headaxes",		"false",		SETTING_BOOL,		(void*)&eth32.settings.drawHeadAxes,
		"enable hitbox axis drawing",
	},
	{ "bodyhitbox",		"false",		SETTING_BOOL,		(void*)&eth32.settings.drawBodyHitbox,
		"enable body hitbox drawing",
	},
	{ "debugpoints",		"false",		SETTING_BOOL,		(void*)&eth32.settings.debugPoints,
		"enable drawing of generated aimpoints",
	},
	{ "bulletrail",		"false",		SETTING_BOOL,		(void*)&eth32.settings.drawBulletRail,
		"enable bullet tracers",
	},
	{ "railwallhack",	"false",		SETTING_BOOL,		(void*)&eth32.settings.railWallhack,
		"see bullet tracers through walls",
	},
	{ "colorheadhb",	"0 1 0",		SETTING_VEC3,		(void*)eth32.settings.colorHeadHitbox,
		"set the color of the head hitbox",
	},
	{ "colorbodyhb",	"1 0 0",		SETTING_VEC3,		(void*)eth32.settings.colorBodyHitbox,
		"set the color of the body hitbox",
	},
	{ "colorbulletrail",	"1 0 0",		SETTING_VEC3,		(void*)eth32.settings.colorBulletRail,
		"set the color of bullet tracers",
	},
	{ "colorxaxis",		"1 0 0",		SETTING_VEC3,		(void*)eth32.settings.colorXAxis,
		"set the color of hitbox x-axis",
	},
	{ "coloryaxis",		"0 1 0",		SETTING_VEC3,		(void*)eth32.settings.colorYAxis,
		"set the color of hitbox y-axis",
	},
	{ "colorzaxis",		"0 0 1",		SETTING_VEC3,		(void*)eth32.settings.colorZAxis,
		"set the color of hitbox z-axis",
	},	
	{ "headhbtime",		"40",			SETTING_INT,		(void*)&eth32.settings.headRailTime,
		"set head hitbox stay time (in msec)",
		0, 1000,
	},
	{ "bodyhbtime",		"40",			SETTING_INT,		(void*)&eth32.settings.bodyRailTime,
		"set body hitbox stay time (in msec)",
		0, 1000,
	},
	{ "xhaircolor",		"0 1 0",			SETTING_VEC3,		(void*)&eth32.settings.xhairColor,
		"sets the crosshair color",
	},
	{ "missilecolor",		"1 1 1",		SETTING_VEC3,		(void*)&eth32.settings.missileEsp,
		"set the missile esp color",
	},
	{ "gui_titlecolor",		"1 1 1 1",		SETTING_VEC4,		(void*)&eth32.guiAssets.titleColor,
		"set the gui text title color",
	},
	{ "gui_textcolor1",		"1 1 1 1",		SETTING_VEC4,		(void*)&eth32.guiAssets.textColor1,
		"set the gui text color",
	},
	{ "gui_textcolor2",		"1 1 1 1",		SETTING_VEC4,		(void*)&eth32.guiAssets.textColor2,
		"set the gui text color",
	},
	{ "gui_healthhi",		"0 1 0 1",		SETTING_VEC4,		(void*)&eth32.settings.gui_healthHi,
		"set the health bar color for full health",
	},
	{ "gui_healthmd",		"1 1 0 1",		SETTING_VEC4,		(void*)&eth32.settings.gui_healthMd,
		"set the health bar color for half health",
	},
	{ "gui_healthlo",		"1 0 0 1",		SETTING_VEC4,		(void*)&eth32.settings.gui_healthLo,
		"set the health bar color for low health",
	},
	{ "gui_stamina",		"0 0 1 1",		SETTING_VEC4,		(void*)&eth32.settings.gui_stamina,
		"set the stamina bar color",
	},
	{ "gui_charge",			"1 1 1 1",		SETTING_VEC4,		(void*)&eth32.settings.gui_charge,
		"set the charge bar color",
	},
	{ "gui_overheat",		"1 0 0 1",		SETTING_VEC4,		(void*)&eth32.settings.gui_overheat,
		"set the overheat bar color",
	},
	{ "gui_reload",			"1 1 0 1",		SETTING_VEC4,		(void*)&eth32.settings.gui_reload,
		"set the reload bar color",
	},

	{ "reaperhead",			"false",		SETTING_BOOL,		(void*)&eth32.settings.reaperHead,
		 "replace original head model with custom reaper one",
 	},
	{ "hitlerhead",			"false",		SETTING_BOOL,		(void*)&eth32.settings.hitlerHead,
		 "replace original head model with custom hitler one",
 	},
	{ "hitlerbody",			"false",		SETTING_BOOL,		(void*)&eth32.settings.hitlerBody,
		 "replace original body model with custom hitler one",
 	},

	{ "xhairopacity",		"1",			SETTING_FLOAT,		(void*)&eth32.settings.xhairOpacity,
		"sets the crosshair opacity",
		0, 1,
	},
	{ "classespsize",		"14",			SETTING_FLOAT,		(void*)&eth32.settings.clsSize,
		"sets the class icon esp size",
		3, 30,
	},
	{ "classesp",			"1",			SETTING_INT,		(void*)&eth32.settings.classEspType,
		"set the class icon esp style",
		CLS_OFF, CLS_MAX-1,
		{
			{ (int)CLS_STATIC,		"off" },
			{ (int)CLS_STATIC,		"static" },
			{ (int)CLS_DIST,		"distance" },
		},
	},
	{ "oldclassicons",		"false",		SETTING_BOOL,		(void*)&eth32.settings.oldClsIcons,
		"display old class icon esp above player heads",
	},
	{ "bulletrailtime",	"40",			SETTING_INT,		(void*)&eth32.settings.bulletRailTime,
		"set bullet tracer stay time (in msec)",
		0, 1000,
	},

	{ "spoofOs",			"true",			SETTING_BOOL,		(void*)&eth32.settings.etproOs,
		"enable etpro os spoofing\n true = win32, false = linux",
	},
	{ "ircserver",		"irc.rizon.net",SETTING_STRING,		(void*)eth32.settings.ircServer,
		"the IRC server the bot connects to (leave this if you dont know what you are doing)",
	},
	{ "pk3name",		"eth32_v2.pk3",	SETTING_STRING,		(void*)eth32.settings.pk3file,
		"the main eth32 pk3 file name",
	},
	{ "etproGuid",		"0",			SETTING_STRING,		(void*)eth32.settings.etproGuid, 
		"set your custom etpro GUID",
	},
	{ "jaymac",		"",				SETTING_STRING,		(void*)eth32.settings.jayMac,
		"set your custom jaymod MAC address (prevents bans based on MAC)",
	},
	{ "cvarprefix",			"eth_set",		SETTING_STRING,		(void*)eth32.settings.cvarPrefix,
		"set your custom cvar prefix",
	},	
	{ "autocrouch",		"false",		SETTING_BOOL,		(void*)&eth32.settings.autoCrouch,
		"enable auto crouching when target is visible",
	},
	// view values
	{ "vw_origviewvalues",	"false",		SETTING_BOOL,		(void*)&eth32.settings.origViewValues,
		"enable unmodified view calculations",
	},
	{ "vw_interpolatedps",	"true",			SETTING_BOOL,		(void*)&eth32.settings.interpolatedPs,
		"enable interpolated playerstate",
	},
	{ "vw_thirdperson",	"false",		SETTING_BOOL,		(void*)&eth32.settings.thirdPerson,
		"enable third person view",
	},
	{ "vw_damagefeedback",	"false",		SETTING_BOOL,		(void*)&eth32.settings.dmgFeedback,
		"enable damage feedback",
	},
	{ "preaim",		"false",		SETTING_BOOL,			(void*)&eth32.settings.preAim,
		"preaim targets",
	},
	{ "preaimtime",		"400.0",		SETTING_FLOAT,			(void*)&eth32.settings.preAimTime,
		"preaim time - higher is earlier aiming",
		0, 5000,
	},

	{ "preshoot",		"false",		SETTING_BOOL,			(void*)&eth32.settings.preShoot,
		"pre-shoot at targets before they are logically visible",
	},
	{ "preshoottime",	"50.0",			SETTING_FLOAT,			(void*)&eth32.settings.preShootTime,
		"preshoot time - higher means earlier shot (and higher chance of miss)",
		0, 5000,
	},
	{ "autopredbots", 		"true", 		SETTING_BOOL, 		(void*)&eth32.settings.autoPredictBots,
		"auto adjust target prediction if target is an OmniBot",
	},
	{ "autopush",		"0",			SETTING_INT,	(void*)&eth32.settings.autoPush,
		"enable auto push players",
		0, MAX_AUTOPUSH-1,
	{
			{ (int)AUTOPUSH_OFF,	"off" },
			{ (int)AUTOPUSH_ENEMY,	"enemy" },
			{ (int)AUTOPUSH_TEAM,	"team" },
			{ (int)AUTOPUSH_BOTH,	"both" },
		},
	},
	{ "autopush_dist",	"96.0",			SETTING_FLOAT,	(void*)&eth32.settings.autoPushDistance,
		"maximum distance to player before pushing",
		0.0, 256.0,
	},
	{ "animcor", "0.0", SETTING_FLOAT, (void*)&eth32.settings.animCorrection,
		"animation correction for aimbot",
		-10.0, 10.0,
	},
	{ "bannerfmt", 			"[N] ^2- ^9name: ^7[n] ^2- ^9ping: ^2[P] &&^9kills: ^7[k] ^2- ^9deaths: ^7[d] ^2- ^9spree: ^7[S] &&^9headshots: ^7[/] ^2- ^9accuracy: ^7[\\]% ^2- ^9hs/kill: ^7[<]", SETTING_STRING, (void*)eth32.settings.BannerFmt,
		"banner format",
	},
	{ "bannerscale", "1.4", SETTING_FLOAT, (void*)&eth32.settings.BannerScale,
		"Banner font scale",
	},	
	{ "gui_banner", "true", SETTING_BOOL, (void*)&eth32.settings.guiBanner,
		"GUI: show stats banner",
	},
	{ "gui_chat", "true", SETTING_BOOL, (void*)&eth32.settings.guiChat,
		"GUI: show eth32 chat window",
	},
	{ "gui_cp", "true", SETTING_BOOL, (void*)&eth32.settings.guiCenterPrint,
		"GUI: show centerprint banner",
	},
	{ "gui_cpanim", "true", SETTING_BOOL, (void*)&eth32.settings.guiCenterPrintAnim,
		"GUI: do centerprint animation",
	},
	{ "gui_cpscale", "1.0", SETTING_FLOAT, (void*)&eth32.settings.guiCenterPrintScale,
		"GUI: centerprint font scale",
		0.0, 10.0,
	},
	{ "gui_orig", "false", SETTING_BOOL, (void*)&eth32.settings.guiOriginal,
		"GUI: use original ET hud",
	},
	
	// namesteal stuff
	{ "namesteal", "false", SETTING_BOOL, (void*)&eth32.settings.doNamesteal, 
		"Enable namestealing",
	}, 
	{ "namesteal_grace", "1000", SETTING_INT, (void*)&eth32.settings.NamestealGrace, 
		"Time to wait in ms to start stealing after joining a server",
		0, 10000,		
	},
	{ "namesteal_mode", "2", SETTING_INT, (void*)&eth32.settings.NamestealMode, 
		"Type of namestealing to do",
		0, NAMESTEAL_MAX-1,
		{ 
			{ (int)NAMESTEAL_TEAM,	"team" },
			{ (int)NAMESTEAL_ENEMY,	"enemy" },
			{ (int)NAMESTEAL_ALL,	"all" },
			{ (int)NAMESTEAL_FILE,	"file" },
		},					
	},
	{ "namesteal_delay", "5000", SETTING_INT, (void*)&eth32.settings.NamestealDelay,
		"Time to wait between changing names (in ms)",
		0, 999999999,
	},
	{ "disguised", 		"false", SETTING_BOOL, (void *)&eth32.settings.drawDisguised,
		"draw disguised ESP on players",
	},
	{ "panzersuicide",	"false",	SETTING_BOOL,	(void*)&eth32.settings.panzerSuicide,
		"auto suicide if we are about to be panzernoobed",
	},
	{ "panzerdistance",	"300",		SETTING_FLOAT,	(void*)&eth32.settings.panzerImpactDist,
		"max distance from impactpoint to procede with panzer suicide",
		40.0f, 500.0f,
	},
	{ "grenadedlight",	"true",		SETTING_BOOL,	(void*)&eth32.settings.grenadeDlight,
		"extra grenade lights inidicating blast area",	
	},
	{ "mortardlight",	"true",		SETTING_BOOL,	(void*)&eth32.settings.mortarDlight,
		"extra mortar lights inidicating blast area",	
	},
	{ "mortartrace",	"true",		SETTING_BOOL,	(void*)&eth32.settings.mortarTrace,
		"show mortar trace lines and impact ESP",	
	},
	{ "artymarkers",	"true",		SETTING_BOOL,	(void*)&eth32.settings.artyMarkers,
		"show arty blast area lights and ESP",	
	},
	{ "panzersuicide",	"false",	SETTING_BOOL,	(void*)&eth32.settings.panzerSuicide,
		"auto suicide if we are about to be panzernoobed",
	},
	{ "panzerdistance",	"300",		SETTING_FLOAT,	(void*)&eth32.settings.panzerImpactDist,
		"max distance from impactpoint to procede with panzer suicide",
		40.0f, 500.0f,
	},
};
